server:
  port: 31500
spring:
  application:
    name: xc-service-manage-order
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xc_order?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
#rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
alipay:
  pay:
    gatewayUrl: https://openapi.alipaydev.com/gateway.do  #支付宝网关
    appid: 2016101800715817    #商户应用id
    app-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCd2CNbJh6t/goAVMb5VCS9dxlZF9VpPo2ZA5vp3rra+Y+Hhqgw8ZwcQKI0qEm+u0w1MLrbUIWfaw93MqmzeY+lmj+flzawznBkPz93YB2dO2GO4cyRWdWFH/7fTQ2aFRGszD5BOq1YhPwI8Tvidvwo6Ad7rQ7Hpw1s7dFvzGKyMNRUmmN7Pf453c/eVLKs+nD8q2JWZXZQRitcMBwxyv/5qCLbLX5sdHo9DRaX5/y0/yAt7NOkK0s45IiLeEjF5OAqGEivvPbf00dVG0EiPVr+BfmgY8NQwWmjp5UIa2J/AkzfUoEh0tvc1/1uVytaQOcSeX6Lw+PpFmw+r5oVgxnbAgMBAAECggEADhvdvS4BHAhTGIh7aJnu1sioiWAqAUhIG99ItnTkOuKHw9NzgTx3eccFOLO6M8RGIZMDgMsHxqIpNbxfkt1Qy7qn6Tn494DcZvmIUMFUpFNEeyMPyAZBoa6kd41Jo/YyKEHxZp86E2l/pcT6V1nPXFCxKorjgVEbUBtJ1zZrtAWpR+QYc7kcP9WCnUVnvBU+piGm/V0oqbrqZxZ8AESG3IVQUt6JXSCPyjkDwQ3gNhVZgQo661riGF75trqgpSamtRXI50fZYXTj5XTeycO3HxrcuMUtEMTVkk86QN8nArFH21wAzz59oe16XAb4Tb/oNJ+xzqkM3edJXwk/NoqukQKBgQDZwyzMSkQrpc6nBwFhB2iA6aFjsvJWKsM16ul9oNOpzZpXd22UKFN9e2KVH5WGCmrOnoRzaqH+5vtdc6qZl0yfLuOaRdJ0P4MJI7Rnsj3MRLoGqA7ptdd3qS0f+twHD8UtmPaCwWhE7BS6jVD3sHMSUDudXz4Scp09gZy2GmoPRwKBgQC5j4hSEHtEEnPqDW0lWzxW4t4R6O18qo46UKLeP9WM1wEVlffXk6r0a0chf/E3psC8nER0m4W9Gdbly9YaK+qBUg/MWJPdurJsadRwyizK/sgnmh3hpgSs4Yit3B3Tyyw6x0h+4+Y5k7f5TurrADw4uSgCoiDNZo89UhEhsh8yzQKBgQCdlZIbnDrM40YytO0YjEXh1DAId/zKwlNV91NUqEfD/5eLaE+SAcS5b8qdY6fOwkcckrYC1823KuwIaqWwVD8MiuAGSjTMDxICUSZCTEhQRAPiwUdZdVAhtfmDxQPo0E6+eo0ZfmC4T6eIgK9xLu12+TzK25uNugdz9RG07lSGDQKBgFrJ2DfWqojewmn0kb9iST51l5OJtJB3Xkk35Mf60YAsPfKSwoVuUYlu54mDcMD6zHg7uN6YrTGdb+BU//ckH4OQY/xmJkqpKt0SVoes04eqasG9jPs3YDg5zMbL2KgkUwqbMGQtGxp2pN/M9fFu1wglx2aqboQwtsqY2Zrz7IHNAoGBANMlyQplRoCghqCVUaqj6dwAnTBIeJWaIzj9EDJrw2UjolwvNYPKySkHNer8WIg9yaFJSdGhcu5pCsF3TbiqLbpjZQxy2B6m2+ULJLjwRqfrYRxXnXKfxnR66Khvc8kd8hC5fN7EiGVNykXVjLtOzCMlqdJ5GtREyNelgN207dh6
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAluzv7i/askkcqEnCWv2HUEct7ntuCsBZ3ymjgBjOU0lI81rVe0hHvpKR8kWHXYuFLO4ItYpO6KaCgj6/wkgwnW/K8MnoVMUyC7IcJz7vFG4S+0FlVnzo+kMdRJEmDLJLei0wa08oGo+Q2z2GUB7QmDqJ2oKdFj17AHI5m5qi99mXS1uowguBtxuFbgPZoUwrg4+RlQUN+r8yGV9dNxqYhup4VSqQqB7/27yieFWyXDSqZMum0PLJ+4F4+GaKJ6pCvvQehCbkQmnWoA2wZQpTvVnUoaysebBV4nt+3J8fhoFSyakcJ+qWn10vWloyme9j1Zr+xnSGkehOpcOBimCHIQIDAQAB
    notify-url: http://yok.ngrok2.xiaomiqiu.cn/order/pay/aliPayNotifyNotice  #支付成功的异步通知回调接口
    return-url: http://yok.ngrok2.xiaomiqiu.cn/order/pay/aliPayReturnNotice   #支付成功的同通知回调接口
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: http://localhost:50101/eureka/,http://localhost:50102/eureka/
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间

